<a href="https://colab.research.google.com/github/brettfazio/AI-Homework/blob/master/HW_4/Homework4_problem2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Problem 2
*Using only numpy, implement the function maxpooling2d. It takes as input input_mat and s and outputs output_mat. The variables input_mat and output_mat are square matrices and s is an integer. It should compute the maxpooling operation on input_mat using window of shape s times s.*



In [0]:
# imports
import numpy as np

In [0]:
def maxpooling2d(input_mat, s):
  if (s > input_mat.shape[0]):
    raise Exception('Invalid maxpooling input, s is larger than the input matrix.')
  
  w = input_mat.shape[0]

  new_size = int(w / s)

  output_mat = np.zeros((new_size, new_size))

  for d in np.arange(new_size):
    for a in np.arange(new_size):
      # Set up our initial value.
      output_mat[d][a] = input_mat[d*s][a*s]
      for i in np.arange(s):
        for j in np.arange(s):
          output_mat[d][a] = max(output_mat[d][a], input_mat[i+d*s][j+a*s])

  return output_mat

Now I will test the function on a few test cases

This first test case is a valid case that shows off proper padding and returns a valid answer.

In [16]:

my_matrix = np.arange(25).reshape(5,5)

print("Input matrix:")
print(my_matrix)

print("s = 2")

my_result = maxpooling2d(my_matrix, 2)

print("Resulting matrix:")
print(my_result)


Input matrix:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
s = 2
Resulting matrix:
[[ 6.  8.]
 [16. 18.]]


This second case is an invalid case that throws my custom exception.

In [17]:
my_small_matrix = np.arange(16).reshape(4,4)

print("Input matrix:")
print(my_small_matrix)

print("s = 10")

my_result = maxpooling2d(my_small_matrix, 10)

Input matrix:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
s = 10


Exception: ignored