<a href="https://colab.research.google.com/github/brettfazio/AI-Homework/blob/master/HW_4/hw4_problem1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Problem 1**

*Using only numpy, implement the function conv2d. It takes as input input_mat and kernel_mat and outputs output_mat. All variables are square matrices. It should compute the convolution of input_mat with the kernel kernel_mat using valid padding.*

So in this notebook I will make a function `conv2d` that takes in two square matrice and computes the convolution *or* produces an error if a convolution cannot be created.

In [0]:
# Imports
import numpy as np

In [0]:
def conv2d(input_mat, kernel_mat):
  # Make sure that a valid convolution can be made
  if (kernel_mat.shape[0] > input_mat.shape[0]):
    raise Exception('Invalid convolution input, kernel is larger than the input matrix.')

  W = kernel_mat.shape[0] # Window size

  new_size = input_mat.shape[0] - W + 1

  output = np.zeros((new_size, new_size))

  # compute the convolution
  for d in np.arange(new_size):
    for a in np.arange(new_size):
      for i in np.arange(W):
        for j in np.arange(W):
          output[d][a] += kernel_mat[i][j] * input_mat[d+i][a+j]

  return output

Now I will use the above function with a basic 1x1 kernel.

In [22]:
input_matrix = np.random.rand(5,5)

print("Input Matrix:")
print(input_matrix)

kernel_one_by_one = np.array([[1]])

resulting_matrix = conv2d(input_matrix, kernel_one_by_one)

# Resulting matrix should be the same as the input matrix
print("Resulting Matrix:")
print(resulting_matrix)

Input Matrix:
[[0.84480632 0.72474711 0.86516843 0.50692553 0.98327827]
 [0.10090673 0.16684281 0.35413952 0.76586938 0.91065362]
 [0.8670508  0.02429372 0.4476776  0.16165474 0.81463785]
 [0.19772909 0.12350448 0.81646179 0.37913485 0.49336829]
 [0.73328811 0.89457122 0.0475502  0.41526678 0.66689977]]
Resulting Matrix:
[[0.84480632 0.72474711 0.86516843 0.50692553 0.98327827]
 [0.10090673 0.16684281 0.35413952 0.76586938 0.91065362]
 [0.8670508  0.02429372 0.4476776  0.16165474 0.81463785]
 [0.19772909 0.12350448 0.81646179 0.37913485 0.49336829]
 [0.73328811 0.89457122 0.0475502  0.41526678 0.66689977]]


Now I will use an kernel matrix that trims away the outside of the input matrix.

In [23]:
input_matrix = np.arange(36).reshape(6,6)

print("Input Matrix:")
print(input_matrix)

kernel_cut = np.array([[0,0,0],[0,1,0],[0,0,0]])

resulting_matrix = conv2d(input_matrix, kernel_cut)

# Resulting matrix should be the same as the input matrix but with the outside
# dropped.
print("Resulting Matrix:")
print(resulting_matrix)

Input Matrix:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
Resulting Matrix:
[[ 7.  8.  9. 10.]
 [13. 14. 15. 16.]
 [19. 20. 21. 22.]
 [25. 26. 27. 28.]]


Now I will test an invalid matrix. In this example the 

In [24]:
input_matrix = np.arange(4).reshape(2,2)

print("Input Matrix:")
print(input_matrix)

kernel_fail = np.zeros((3,3))

resulting_failure = conv2d(input_matrix, kernel_fail)

# should see an exception produced.

Input Matrix:
[[0 1]
 [2 3]]


Exception: ignored